#!/usr/bin/env python3
"""
Transcription bridge for the Concord pipeline.

Usage:
    transcribe.py <audio_path> <output_md_path> [--model large-v3] [--language en] [--device cuda] [--compute-type float16] [--beam-size 5]

Takes an audio file and produces a markdown transcript with timestamps,
suitable for indexing with QMD.
"""

import argparse
import json
import os
import sys
import time


def format_timestamp(seconds: float) -> str:
    """Format seconds as HH:MM:SS."""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    if hours > 0:
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


def transcribe(
    audio_path: str,
    output_path: str,
    model_name: str = "large-v3",
    language: str = "en",
    device: str = "cuda",
    compute_type: str = "float16",
    beam_size: int = 5,
):
    from faster_whisper import WhisperModel

    print(f"[transcribe] Loading model '{model_name}' on {device} ({compute_type})...")
    t_start = time.time()

    model = WhisperModel(
        model_name,
        device=device,
        compute_type=compute_type,
    )

    t_load = time.time() - t_start
    print(f"[transcribe] Model loaded in {t_load:.1f}s")

    # Transcribe
    print(f"[transcribe] Transcribing: {audio_path}")
    t_trans_start = time.time()

    segments, info = model.transcribe(
        audio_path,
        language=language,
        beam_size=beam_size,
        vad_filter=True,
        word_timestamps=True,
    )

    # Detect language
    detected_lang = info.language
    lang_prob = info.language_probability
    print(f"[transcribe] Detected language: {detected_lang} ({lang_prob:.2%})")
    print(f"[transcribe] Duration: {info.duration:.1f}s")

    # Collect segments
    all_segments = []
    full_text_parts = []

    for segment in segments:
        all_segments.append({
            "start": segment.start,
            "end": segment.end,
            "text": segment.text.strip(),
        })
        full_text_parts.append(segment.text.strip())
        elapsed = time.time() - t_trans_start
        pct = (segment.end / info.duration) * 100 if info.duration > 0 else 0
        print(f"\r[transcribe] {pct:.0f}% | {format_timestamp(segment.end)}/{format_timestamp(info.duration)} | {elapsed:.0f}s elapsed", end="", flush=True)

    t_trans = time.time() - t_trans_start
    print(f"\n[transcribe] Transcription complete in {t_trans:.1f}s ({info.duration / t_trans:.1f}x realtime)")

    # Build markdown
    audio_basename = os.path.splitext(os.path.basename(audio_path))[0]

    md_lines = [
        f"# Transcript: {audio_basename}",
        "",
        f"- **Model**: {model_name}",
        f"- **Language**: {detected_lang} ({lang_prob:.0%} confidence)",
        f"- **Duration**: {format_timestamp(info.duration)}",
        f"- **Segments**: {len(all_segments)}",
        f"- **Transcribed at**: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## Full Text",
        "",
        " ".join(full_text_parts),
        "",
        "---",
        "",
        "## Timestamped Segments",
        "",
    ]

    # Add timestamped segments
    for seg in all_segments:
        ts = f"[{format_timestamp(seg['start'])} → {format_timestamp(seg['end'])}]"
        md_lines.append(f"- {ts} {seg['text']}")

    md_lines.append("")
    md_lines.append("---")
    md_lines.append("")
    md_lines.append("*Generated by Concord pipeline*")

    # Write markdown file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    print(f"[transcribe] Saved transcript to: {output_path}")

    # Also save JSON metadata
    json_path = output_path.rsplit(".", 1)[0] + ".json"
    metadata = {
        "schema_version": 2,
        "model": model_name,
        "language": detected_lang,
        "language_probability": lang_prob,
        "duration_seconds": info.duration,
        "duration_formatted": format_timestamp(info.duration),
        "segment_count": len(all_segments),
        "load_time_seconds": round(t_load, 1),
        "transcription_time_seconds": round(t_trans, 1),
        "realtime_factor": round(info.duration / t_trans, 1) if t_trans > 0 else 0,
        "word_count": sum(len(seg["text"].split()) for seg in all_segments),
        "text": " ".join(full_text_parts),
        "segments": all_segments,
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    return metadata


def main():
    parser = argparse.ArgumentParser(description="Transcribe audio to markdown")
    parser.add_argument("audio_path", help="Path to audio file (WAV, MP3, etc.)")
    parser.add_argument("output_path", help="Path for output markdown file")
    parser.add_argument("--model", default="large-v3", help="Whisper model name")
    parser.add_argument("--language", default="en", help="Language code")
    parser.add_argument("--device", default="cuda", help="Device: cuda or cpu")
    parser.add_argument("--compute-type", default="float16", help="Compute type")
    parser.add_argument("--beam-size", type=int, default=5, help="Beam size")
    parser.add_argument("--json", action="store_true", help="Output metadata as JSON to stdout")

    args = parser.parse_args()

    if not os.path.exists(args.audio_path):
        print(f"Error: Audio file not found: {args.audio_path}", file=sys.stderr)
        sys.exit(1)

    metadata = transcribe(
        args.audio_path,
        args.output_path,
        model_name=args.model,
        language=args.language,
        device=args.device,
        compute_type=args.compute_type,
        beam_size=args.beam_size,
    )

    if args.json:
        print(json.dumps(metadata))


if __name__ == "__main__":
    main()
